language: node_js
node_js:
  - '14'
cache:
  yarn: true
  directories:
    - demo/node_modules
script:
  - cd demo
  - yarn
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: demo/build
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: main
